export const SIGNIN_GOOGLE_REQUEST = "SIGNIN_GOOGLE_REQUEST";
export const SIGNIN_REQUEST = "SIGNIN_REQUEST";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILURE = "SIGNIN_FAILURE";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const SIGNOUT_REQUEST = "SIGNOUT_REQUEST"
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS"
export const SIGNOUT_FAILURE = "SIGNOUT_FAILURE"

export const HANDLE_AUTH_STATE_CHANGE_REQUEST = "HANDLE_AUTH_STATE_CHANGE_REQUEST"
export const HANDLE_AUTH_STATE_CHANGE_SUCCESS = "HANDLE_AUTH_STATE_CHANGE_SUCCESS"
export const HANDLE_AUTH_STATE_CHANGE_FAILURE = "HANDLE_AUTH_STATE_CHANGE_FAILURE"