export const LOAD_STAGE_REQUEST = "LOAD_STAGE_REQUEST"
export const LOAD_STAGE_SUCCESS = "LOAD_STAGE_SUCCESS"
export const LOAD_STAGE_FAILURE = "LOAD_STAGE_FAILURE"

export const CREATE_STAGE_REQUEST = "CREATE_STAGE_REQUEST"
export const CREATE_STAGE_SUCCESS = "CREATE_STAGE_SUCCESS"
export const CREATE_STAGE_FAILURE = "CREATE_STAGE_FAILURE"

export const DELETE_STAGE_REQUEST = "DELETE_STAGE_REQUEST"
export const DELETE_STAGE_SUCCESS = "DELETE_STAGE_SUCCESS"
export const DELETE_STAGE_FAILURE = "DELETE_STAGE_FAILURE"

export const STAGE_STARTDATE_UPDATE_REQUEST = "STAGE_STARTDATE_UPDATE_REQUEST"
export const STAGE_STARTDATE_UPDATE_SUCCESS = "STAGE_STARTDATE_UPDATE_SUCCESS"
export const STAGE_STARTDATE_UPDATE_FAILURE = "STAGE_STARTDATE_UPDATE_FAILURE"

export const STAGE_ENDDATE_UPDATE_REQUEST = "STAGE_ENDDATE_UPDATE_REQUEST"
export const STAGE_ENDDATE_UPDATE_SUCCESS = "STAGE_ENDDATE_UPDATE_SUCCESS"
export const STAGE_ENDDATE_UPDATE_FAILURE = "STAGE_ENDDATE_UPDATE_FAILURE"

export const UPDATE_STAGE_NAME_REQUEST = "UPDATE_STAGE_NAME_REQUEST"
export const UPDATE_STAGE_NAME_SUCCESS = "UPDATE_STAGE_NAME_SUCCESS"
export const UPDATE_STAGE_NAME_FAILURE = "UPDATE_STAGE_NAME_FAILURE"

export const CLEAR_STAGES = "CLEAR_STAGES"
export const SET_CURRENT_STAGE = "SET_CURRENT_STAGE"
export const CLEAR_CURRENT_STAGE = "CLEAR_CURRENT_STAGE"