export const LOAD_BOARDS_REQUEST = "LOAD_BOARDS_REQUEST"
export const LOAD_BOARDS_SUCCESS = "LOAD_BOARDS_SUCCESS"
export const LOAD_BOARDS_FAILURE = "LOAD_BOARDS_FAILURE"

export const CREATE_BOARD_REQUEST = "CREATE_BOARD_REQUEST"
export const CREATE_BOARD_SUCCESS = "CREATE_BOARD_SUCCESS"
export const CREATE_BOARD_FAILURE = "CREATE_BOARD_FAILURE"

export const DELETE_BOARD_REQUEST = "DELETE_BOARD_REQUEST"
export const DELETE_BOARD_SUCCESS = "DELETE_BOARD_SUCCESS"
export const DELETE_BOARD_FAILURE = "DELETE_BOARD_FAILURE"

export const LOAD_CARD_REQUEST = "LOAD_CARD_REQUEST"
export const LOAD_CARD_SUCCESS = "LOAD_CARD_SUCCESS"
export const LOAD_CARD_FAILURE = "LOAD_CARD_FAILURE"

export const CREATE_CARD_REQUEST = "CREATE_CARD_REQUEST"
export const CREATE_CARD_SUCCESS = "CREATE_CARD_SUCCESS"
export const CREATE_CARD_FAILURE = "CREATE_CARD_FAILURE"

export const UPDATE_CARD_REQUEST = "UPDATE_CARD_REQUEST"
export const UPDATE_CARD_SUCCESS = "UPDATE_CARD_SUCCESS"
export const UPDATE_CARD_FAILURE = "UPDATE_CARD_FAILURE"

export const DELETE_CARD_REQUEST = "DELETE_CARD_REQUEST"
export const DELETE_CARD_SUCCESS = "DELETE_CARD_SUCCESS"
export const DELETE_CARD_FAILURE = "DELETE_CARD_FAILURE"