export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST"
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS"
export const CREATE_PROJECT_FAILURE = "CREATE_PROJECT_FAILURE"

export const UPDATE_PROJECT_REQUEST = "UPDATE_PROJECT_REQUEST"
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS"
export const UPDATE_PROJECT_FAILURE = "UPDATE_PROJECT_FAILURE"

export const DELETE_PROJECT_REQUEST = "DELETE_PROJECT_REQUEST"
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS"
export const DELETE_PROJECT_FAILURE = "DELETE_PROJECT_FAILURE"


export const MY_PROJECT_REQUEST = "MY_PROJECT_REQUEST"
export const MY_PROJECT_SUCCESS = "MY_PROJECT_SUCCESS"
export const MY_PROJECT_FAILURE = "MY_PROJECT_FAILURE"

export const LOAD_PROJECT_REQUEST = "LOAD_PROJECT_REQUEST"
export const LOAD_PROJECT_SUCCESS = "LOAD_PROJECT_SUCCESS"
export const LOAD_PROJECT_FAILURE = "LOAD_PROJECT_FAILURE"

export const LOAD_PROJECT_MEMBERS_REQUEST = "LOAD_PROJECT_MEMBERS_REQUEST"
export const LOAD_PROJECT_MEMBERS_SUCCESS = "LOAD_PROJECT_MEMBERS_SUCCESS"
export const LOAD_PROJECT_MEMBERS_FAILURE = "LOAD_PROJECT_MEMBERS_FAILURE"

export const SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT"