export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST"
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS"
export const CREATE_PROJECT_FAILURE = "CREATE_PROJECT_FAILURE"

export const MY_PROJECT_REQUEST = "MY_PROJECT_REQUEST"
export const MY_PROJECT_SUCCESS = "MY_PROJECT_SUCCESS"
export const MY_PROJECT_FAILURE = "MY_PROJECT_FAILURE"